package com.example.striderbackend.model;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Activity entity representing a running, cycling, or workout activity.
 *
 * This class maps directly to a database table through JPA annotations.
 * Each instance represents one activity record stored in the database.
 */
@Entity
public class Activity {

    /**
     * Primary key (UUID).
     * Automatically generated by Hibernate when a new Activity is saved.
     */
    @Id
    @GeneratedValue
    private UUID id;

    /**
     * Short title of the activity (e.g., "Morning Run").
     */
    private String title;

    /**
     * Optional longer description of the activity.
     */
    private String description;

    /**
     * Distance completed, measured in kilometers.
     */
    private double distanceKm;

    /**
     * Duration of the activity in minutes.
     */
    private int durationMinutes;

    /**
     * The date when the activity took place (no time, just yyyy-MM-dd).
     */
    private LocalDate date;

    /**
     * Default constructor required by JPA.
     */
    public Activity() {}

    /**
     * Full constructor used to create Activity objects manually.
     * Useful for testing or custom logic.
     */
    public Activity(UUID id, String title, String description, double distanceKm,
                    int durationMinutes, LocalDate date) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.distanceKm = distanceKm;
        this.durationMinutes = durationMinutes;
        this.date = date;
    }

    // --- Getters and Setters (standard POJO methods) ---

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public double getDistanceKm() { return distanceKm; }
    public void setDistanceKm(double distanceKm) { this.distanceKm = distanceKm; }

    public int getDurationMinutes() { return durationMinutes; }
    public void setDurationMinutes(int durationMinutes) { this.durationMinutes = durationMinutes; }

    public LocalDate getDate() { return date; }
    public void setDate(LocalDate date) { this.date = date; }
}
